In [1]:
import pandas as pd

weather_dataset = pd.read_csv("dataIn/weatherHistory.csv")
weather_dataset.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

# Grouping 

When we say grouping we mean to literally combine values that are repetitive into groups (so for example the group with the same Country). In pandas much like in SQL we can do so using the `groupby()` method. As we can see in the example below we can see the maximum temperature for each weather type (breezy, clear, drizzle etc.) using a groupby.

> Note that `groupby()` returns a groupby object which has to have operations made on it, as of that moment after grouping you will have access to all the remaining columns to work with. So in theory it works just like a DataFrame meaning you can apply methods such as `apply()` to it.

You can also groupby multiple columns such as the `Summary` and the `Precip Type` like in the example below. This creates a **Multi-index** which is harder to manage and select data with.

> **DO NOT FORGET** that in order to work with columns resulted by using groupby you must use either an accessor `[]` or `iloc, loc` otherwise operations will be done on the entire DataFrame (max, mean etc.).

In [18]:
print(type(weather_dataset.groupby(by='Summary')["Temperature (C)"].max()))
# print(weather_dataset.groupby(by='Summary')["Temperature (C)"].max())

print("---")

# print(weather_dataset.groupby(by='Summary').apply(lambda df : df["Temperature (C)"].max()))

print(weather_dataset.groupby(by=["Summary", "Precip Type"])["Temperature (C)"].sum())

<class 'pandas.Series'>
---
Summary                              Precip Type
Breezy                               rain              451.233333
                                     snow              -23.444444
Breezy and Dry                       rain               21.111111
Breezy and Foggy                     rain               45.472222
                                     snow              -63.333333
Breezy and Mostly Cloudy             rain             5788.994444
                                     snow              -64.794444
Breezy and Overcast                  rain             3952.527778
                                     snow             -128.955556
Breezy and Partly Cloudy             rain             4843.805556
                                     snow              -21.600000
Clear                                rain           134348.633333
                                     snow            -5448.761111
Dangerously Windy and Partly Cloudy  rain                8.944444
Drizzle                              rain              423.055556
Dry                                  rain              988.844444
Dry and Mostly Cloudy                rain              375.738889
Dry and Partly Cloudy                rain             2288.094444
Foggy                                rain            21263.516667
                                     snow           -10978.572222
Humid and Mostly Cloudy              rain              835.455556
Humid and Overcast                   rain              150.605556
Humid and Partly Cloudy              rain              366.661111
Light Rain                           rain              631.355556
Mostly Cloudy                        rain           357439.461111
                                     snow            -4841.505556
Overcast                             rain           131861.972222
                                     snow            -7966.811111
Partly Cloudy                        rain           512846.366667
                                     snow            -5493.811111
Rain                                 rain              100.961111
Windy                                rain               54.438889
Windy and Dry                        rain               27.222222
Windy and Foggy                      rain               49.655556
                                     snow               -2.150000
Windy and Mostly Cloudy              rain              414.211111
Windy and Overcast                   rain              360.961111
                                     snow               -3.977778
Windy and Partly Cloudy              rain              667.861111
Name: Temperature (C), dtype: float64

## agg()

You can use the `agg()` function on a groupby object to apply multiple functions to the same groupby object instead of just one, kind of like a `describe()`.

In [19]:
weather_dataset.groupby(by="Summary")["Temperature (C)"].agg(["min", "max", "mean"])

                                           min        max       mean
Summary
Breezy                               -2.777778  37.588889   7.922016
Breezy and Dry                       21.111111  21.111111  21.111111
Breezy and Foggy                     -3.827778  17.616667  -0.510317
Breezy and Mostly Cloudy             -6.966667  27.522222  11.093411
Breezy and Overcast                 -11.533333  22.433333   7.241614
Breezy and Partly Cloudy             -5.050000  38.438889  12.492761
Clear                               -20.000000  39.905556  11.925109
Dangerously Windy and Partly Cloudy   8.944444   8.944444   8.944444
Drizzle                               7.805556  17.844444  10.847578
Dry                                  20.000000  38.750000  29.083660
Dry and Mostly Cloudy                20.072222  33.905556  26.838492
Dry and Partly Cloudy                20.000000  37.800000  26.605749
Foggy                               -21.822222  23.661111   1.464035
Humid and Mostly Cloudy              20.000000  23.111111  20.886389
Humid and Overcast                   20.105556  24.055556  21.515079
Humid and Partly Cloudy              20.055556  23.566667  21.568301
Light Rain                            6.811111  16.011111  10.021517
Mostly Cloudy                       -16.894444  37.155556  12.629334
Overcast                            -16.111111  33.644444   7.516502
Partly Cloudy                       -20.555556  39.588889  16.024782
Rain                                  8.205556  11.500000  10.096111
Windy                                 3.938889  12.172222   6.804861
Windy and Dry                        27.222222  27.222222  27.222222
Windy and Foggy                      -2.150000  19.633333  11.876389
Windy and Mostly Cloudy               3.888889  19.905556  11.834603
Windy and Overcast                   -2.266667  21.305556   7.932963
Windy and Partly Cloudy               1.111111  22.705556   9.968076

## Multi-indexes 

Because multi-indexes are hard to deal with and usually require much more complex manipulation your usual move would be to revert back to a single index using the `reset_index()` function.

In [ ]:
weather_dataset = pd.read_csv("dataIn/weatherHistory.csv")

grouped = weather_dataset.groupby(by=["Summary", "Precip Type"])["Temperature (C)"].sum()
type(grouped.index) # -- Multi-index
 
grouped = grouped.reset_index() # -- Ranged index
type(grouped.index)

pandas.RangeIndex

# Sorting

Here you have two options:
- sort by value -> `sort_values()`
- sort by index -> `sort_index()` 

Both which are pretty self explanatory

In [38]:
weather_dataset["Temperature (C)"].sort_values(ascending=False).head() # - sort descendingly
# weather_dataset.sort_values(by="Temperature (C)", ascending=False) # - same thing as above bt returns the whole dataframe sorted rather than only a series

weather_dataset.sort_index(ascending=False)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
...,...,...,...,...,...,...,...,...,...,...,...,...
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.