In [2]:
import pandas as pd

weather_dataset = pd.read_csv('dataIn/weatherHistory.csv')
weather_dataset.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

# Dtypes

Data types in pandas are represented as `dtypes` and we can view them for each column using `weather_dataset.dtypes`. 

- int -> dtype int64
- float -> dtype float64
- string -> object 
- missing values -> NaN (Not a Number) - for technical reasons it is a float64 


# astype()

We can switch from one dtype to the other using `astype()`

In [ ]:
weather_dataset["Temperature (C)"].astype('int64')

0         9
1         9
2         9
3         8
4         8
         ..
96448    26
96449    24
96450    22
96451    21
96452    20
Name: Temperature (C), Length: 96453, dtype: int64

# Filling NaN values

We can use the `fillna()` function to fill them. On top of this we have the `pd.isnull()`and `pd.notnull()` for returning the NaN values in the DataFrame.

In [ ]:
pd.isnull(weather_dataset)
weather_dataset["Apparent Temperature (C)"].fillna(weather_dataset["Apparent Temperature (C)"].mean())

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,False,False,False,False,False,False,False,False,False,False,False,False
96449,False,False,False,False,False,False,False,False,False,False,False,False
96450,False,False,False,False,False,False,False,False,False,False,False,False
96451,False,False,False,False,False,False,False,False,False,False,False,False
96452,False,False,False,False,False,False,False,False,False,False,False,False

# Replacing values

You can replace values inside a DataFrame using the `replace()` method. This can be useful if you want for example to turn values from `0` to `Unknown` or something else.

In [5]:
weather_dataset["Temperature (C)"].replace(0, "Unknown")

0         9.472222
1         9.355556
2         9.377778
3         8.288889
4         8.755556
           ...
96448    26.016667
96449    24.583333
96450    22.038889
96451    21.522222
96452    20.438889
Name: Temperature (C), Length: 96453, dtype: object